#!/bin/bash

cd "$1"
foldername=${PWD##*/}
foldername2="${foldername,,}"
reponame=${foldername2//[^a-zA-Z0-9]/-}
string={\"name\":\"$reponame\"}
#echo $string


if [ -d .git ]; then
  git update-index -q --refresh
  if test -z "$(git status --porcelain)"; then
    notify-send "github Sync" "Everything is already synced" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
  else  
    git add -A
    git commit -m "Flies modified"
    git ls-remote "git@github.com:khurshid-alam/$reponame.git"
    if [ "$?" -ne 0 ]; then
      curl -XPOST -H 'Authorization: token f71a813636cca0e128dc92cf980646cf662de518' https://api.github.com/user/repos -d $string
      git remote add origin git@github.com:khurshid-alam/$reponame.git
      notify-send "github Sync Starts" "syncing local repo with github" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
      git push origin master
      clone_url="https://github.com/khurshid-alam/$reponame.git"
      echo $clone_url
      notify-send "github Sync" " All files has been syncronized with repo at $clone_url" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
      sleep 4s
      xdg-open $clone_url
    else
      notify-send "github Sync Starts" "syncing local repo with github" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
      git push origin master
      clone_url="https://github.com/khurshid-alam/$reponame.git"
      notify-send "github Sync" " All files has been syncronized with repo at $clone_url" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
      sleep 4s
      xdg-open $clone_url
    fi
  fi
else
  git init
  git add -A
  git commit -m "first commit"
  git ls-remote "https://github.com/khurshid-alam/$reponame.git"
  if [ "$?" -ne 0 ]; then
    curl -XPOST -H 'Authorization: token f71a813636cca0e128dc92cf980646cf662de518' https://api.github.com/user/repos -d $string
    git remote add origin git@github.com:khurshid-alam/$reponame.git
    notify-send "github Sync Starts" "syncing local repo with github" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
    git push origin master
    clone_url="https://github.com/khurshid-alam/$reponame.git"
    echo $clone_url
    notify-send "github Sync" " All files has been syncronized with repo at $clone_url" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
    sleep 4s
    xdg-open $clone_url
  else
    notify-send "github Sync Starts" "syncing local repo with github" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
    git push origin master
    clone_url="https://github.com/khurshid-alam/$reponame.git"
    notify-send "github Sync" " All files has been syncronized with repo at $clone_url" -i "/home/sunny/.icons/AwOkenDark/clear/24x24/apps/github.png"
    sleep 4s
    xdg-open $clone_url
  fi
fi
