#!/bin/bash

cd "$1"
foldername=${PWD##*/}
foldername2="${foldername,,}"
reponame=${foldername2//[^a-zA-Z0-9]/-}
string={\"name\":\"$reponame\"}
echo $foldername2
#echo $string

#gnome-terminal --execute bash -c "'git push origin master';bash"
#gnome-terminal -x bash -c "git push master origin; exec $SHELL"

git ls-remote "git@github.com:khurshid-alam/$reponame66.git"
if [ "$?" -ne 0 ]; then
  echo "repo doesn't exixst"
else
  echo "repo is there!"
fi
